---
classes: 
  - forumone::varnish
  - forumone::nodejs
  - forumone::ruby
  - memcached

forumone::webserver::webserver: nginx

forumone::php::prefix: "php56u"

forumone::php::modules:
  - pecl-memcached
  - gd
  - opcache
