---
classes: 
  - forumone::varnish
  - forumone::nodejs
  - forumone::ruby
  - memcached

forumone::webserver::webserver: nginx

forumone::php::modules:
  - pecl-memcached
  - xcache
  - gd
  
php::modules: 
  xcache: 
    settings: 
      xcache.size: "96M"
