---
classes: 
  - forumone::solr
  - forumone::varnish
  - forumone::nodejs
  - forumone::ruby
  - redis

forumone::webserver::webserver: nginx

forumone::php::prefix: "php56u"

forumone::php::modules:
  - pecl-apc
  - pecl-redis
  
forumone::solr::collections:  
  drupal: 
    order: 1
    
php::modules: 
  apc: 
    pkgname: "pecl-apc"
    settings: 
      apc.shm_size: "96M"
