---
forumone::databases: 
  web: 
    username: web

forumone::webserver::vhosts:  
  vagrant: 
    path: "/vagrant/public"

forumone::solr::collections:  
  drupal: 
    order: 1

forumone::ruby::home: "/usr/local/rbenv"