---
classes: 
  - forumone::webserver
  - forumone::php
  - forumone::drush
  - forumone::mailcatcher

forumone::php::modules:
  - xml
  - pdo
  - mbstring
  - mysqlnd
  - pecl-xdebug
  - gd
  - process

php::ini: 
  display_errors: "On"
  memory_limit: "256M"
  upload_max_filesize: "50M"
  post_max_size: "100M"
  sendmail_path: "/usr/bin/env catchmail"
  max_execution_time: 180

forumone::php::settings:
  realpath_cache_size: "128K"
  realpath_cache_ttl: "7200"
  xdebug.remote_enable: 1
  xdebug.remote_connect_back: 1
  xdebug.remote_handler: "dbgp"
  opcache.memory_consumption: "128M"
  
percona::conf:
  max_allowed_packets:
    content: "[mysqld]\nmax_allowed_packet=100M"
  innodb_file_per_table:
    content: "[mysqld]\ninnodb_file_per_table"
  query_cache_size:
    content: "[mysqld]\nquery_cache_size = 128M"
  table_open_cache:
    content: "[mysqld]\ntable_open_cache = 2048"
  table_cache:
    content: "[mysqld]\ntable_cache = 1024"
  thread_cache:
    content: "[mysqld]\nthread_cache_size = 4"
  memory_buffers:
    content: "[mysqld]\ntmp_table_size = 128\nmax_heap_table_size = 128M\njoin_buffer_size = 1M\nmyisam_sort_buffer_size = 8M\nsort_buffer_size = 2M"